version: 2.1

jobs:
  integration_tests_backend:
    machine: true
    steps:
      - run: echo "intégrer tests du backend"
  deploy_staging:
    machine: true
    steps:
      -run: echo "deploy staging"
  acceptance_tests_1:
    machine: true
    steps:
      - run: echo "acceptance tests 1-5"
  acceptance_tests_2:
    machine: true
    steps:
      - run: echo "acceptance tests 6-10"
  acceptance_tests_3:
    machine: true
    steps:
      - run: echo "acceptance tests 11-15"
  acceptance_tests_4:
    machine: true
    steps:
      - run: echo "acceptance tests 16-20"            
  checkout_and_unit_test:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout
      - run: echo "unit tests"
  deploy_backend:
    machine: true
    steps:
      - run: echo "deploy backend"
  deploy_production:
    machine: true
    steps:
      - run: echo "deploy new version"
workflows:
  build:
    jobs:
      - checkout_and_unit_test
      - deploy_backend:
          requires:
            - checkout_and_unit_test
      - integration_tests_backend:
          requires:
            - deploy_backend
      - deploy_staging:
          requires:
            - integration_tests_backend
      - acceptance_tests_1:
          requires:
            - deploy_staging
      - acceptance_tests_2:
          requires:
            - deploy_staging
      - acceptance_tests_3:
          requires:
            - deploy_staging
      - acceptance_tests_4:
          requires:
            - deploy_staging
      - deploy_production:
          requires:
            - acceptance_tests_1
            - acceptance_tests_2
            - acceptance_tests_3
            - acceptance_tests_4
